apiVersion: v1
kind: Service
metadata:
  name: {{ include "python.name" . }}
  labels:
    {{- include "python.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "python.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.pythonMicroservice.container.port }}
  type: ClusterIP

